server:
  port: 10010
spring:
  application:
    name: gateway # Ӧ�����ƣ�����Eureka����ʾ
eureka:
  client:
    service-url: # EurekaServer�ĵ�ַ���������Լ��ĵ�ַ������Ǽ�Ⱥ����Ҫ��������Server�ĵ�ַ��
      defaultZone: http://127.0.0.1:10086/eureka